global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100', '10.10.3.82:9100']
  - job_name: 'openvpn'
    static_configs:
      - targets: ['10.10.3.82:9176']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - tcp://10.10.3.82:1194
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: 'pki_health'
    static_configs:
      - targets: ['10.10.3.82:8080']

